name: volunteering_kemsu
description: "Приложение для волонтёрского центра, сделано для обучения."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  logger: ^2.6.0
  provider: ^6.1.5
  image: ^4.5.4
  http: ^1.4.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  pin_code_fields: ^8.0.1
  flutter_local_notifications: ^19.3.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  json_serializable: ^6.9.5
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  percent_indicator: ^4.2.5
  syncfusion_flutter_datepicker: ^30.1.39
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  flutter_image_slideshow: ^0.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  dialog_page: ^1.0.0


flutter:
  uses-material-design: true
